In [138]:
from scipy.optimize import fmin as optim
import numpy as np

In [139]:
def minis(xy, points, p):
    
    def ft(a):
        a = a.reshape(p,2)
        coords = np.matmul(xy,a)
        dists = np.sum((coords - points)**2, axis = 1)
        return sum(dists)
    
    transfer = optim(ft, np.ones([p,2]))
    transfer = transfer.reshape(p,2)
    print(transfer)
    C = np.matmul(xy, transfer)
    return C 

In [158]:
import pandas as pd
data = pd.read_csv("khc01221.txt")

In [159]:
data.head()

ATT      ADT     ALX     ALY  ARI     APW     APH  AQU     AFX     BTT  \
0  0.0000   0.0000  0.2349  0.1531   -1  0.2055  0.1947    1  0.0167 -0.0016   
1  0.0456  45.6178  0.2377  0.1022   -1  0.2315  0.1978    1  0.0623  0.0436   
2  0.0500   4.3726  0.2624  0.3642   -1  0.2045  0.1318    1  0.0044  0.0485   
3  0.0667  16.7552  0.2513  0.1160   -1  0.2567  0.2101    1  0.0168  0.0651   
4  0.0834  16.6555  0.2566  0.0306   -1  0.2800  0.2289    1  0.0167  0.0818   

       BDT     BLX     BLY  BRI     BPW     BPH  BQU     BFX  CNT   MRK  
0  -1.6466  0.3625 -0.0238   -1  0.2552  0.2234    1  0.0166    0  +,+"  
1  45.2731  0.3630 -0.0154   -1  0.2483  0.2175    1  0.0453    1     "  
2   4.8696  0.3616  0.0083   -1  0.2522  0.2174    1  0.0049    2     "  
3  16.6164  0.3676  0.0187   -1  0.2462  0.2124    1  0.0166    3     "  
4  16.7150  0.3632  0.0060   -1  0.2404  0.2106    1  0.0167    4     "

In [160]:
temp = pd.DataFrame(pd.DataFrame({"X": data.ALX.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)],
                            "Y": data.ALY.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)]}).apply(np.mean)).transpose()
temp = pd.concat([temp, pd.DataFrame(pd.DataFrame({"X": data.ALX.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)],
                            "Y": data.ALY.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)]}).apply(np.median)).transpose()])

In [162]:
def timecut(data):
    temps = pd.DataFrame()
    x=[0.1,11/30,0.9,0.1,0.9,0.9,0.1,19/30,19/30,11/30,19/30,11/30,11/30,0.9,0.1,19/30]
    y = [0.1,19/30,0.9,11/30,19/30,0.1,0.9,0.9,0.1,0.9,19/30,0.1,11/30,11/30,19/30,11/30]
    for i in range(0, 16):
        temp = pd.DataFrame({"X": data.ALX.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)],
                            "Y": data.ALY.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)]})
        temp = pd.concat([temp.reset_index(), pd.DataFrame( {"x":[x[i]]*temp.shape[0]} ), pd.DataFrame({"y":[y[i]]*temp.shape[0]}) ], axis = 1)
        temps = pd.concat([temps, temp])
    return temps

def timemean(data):
    temps = pd.DataFrame()
    x=[0.1,11/30,0.9,0.1,0.9,0.9,0.1,19/30,19/30,11/30,19/30,11/30,11/30,0.9,0.1,19/30]
    y = [0.1,19/30,0.9,11/30,19/30,0.1,0.9,0.9,0.1,0.9,19/30,0.1,11/30,11/30,19/30,11/30]
    for i in range(0, 16):
        temp = pd.DataFrame(pd.DataFrame({"X": data.ALX.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)],
                            "Y": data.ALY.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)]}).apply(np.mean)).transpose()
        temp = pd.concat([temp, pd.DataFrame( {"x":[x[i]]*temp.shape[0]} ), pd.DataFrame({"y":[y[i]]*temp.shape[0]}) ], axis = 1)
        temps = pd.concat([temps, temp])
    return temps

def times(data):
    temps = pd.DataFrame()
    x=[0.1,11/30,0.9,0.1,0.9,0.9,0.1,19/30,19/30,11/30,19/30,11/30,11/30,0.9,0.1,19/30]
    y = [0.1,19/30,0.9,11/30,19/30,0.1,0.9,0.9,0.1,0.9,19/30,0.1,11/30,11/30,19/30,11/30]
    for i in range(0, 16):
        temp = pd.DataFrame(pd.DataFrame({"X": data.ALX.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)],
                            "Y": data.ALY.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)]}).apply(np.mean)).transpose()
        temp = pd.concat([temp, pd.DataFrame(pd.DataFrame({"X": data.ALX.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)],
                            "Y": data.ALY.loc[(data.ATT >= 2 + 5 * i) & (data.ATT < 7  + 5 * i)]}).apply(np.median)).transpose()])
        temp = pd.concat([temp.reset_index(), pd.DataFrame( {"x":[x[i]]*temp.shape[0]} ),  pd.DataFrame({"y":[y[i]]*temp.shape[0]}) ], axis = 1)
        temps = pd.concat([temps, temp])
    return temps


In [163]:
a = timecut(data)
b = timemean(data)
c = times(data)

In [164]:
coords = np.array([[0.5,x,y, x*y, x**2, y**2] for x, y in zip(a.X, a.Y)])
points = np.array([[x,y] for x, y in zip(a.x, a.y)])

In [137]:
sdw = minis(coords, points,6)

[[ 0.68166882  1.09895474]
 [-1.1189841  -0.86331957]
 [ 2.73571935  1.03733348]
 [ 3.22747054  0.90049702]
 [-0.56690243  0.08990023]
 [-2.85187969 -0.85348067]]


In [171]:
coords = np.array([[0.5,x,y, x*y] for x, y in zip(b.X, b.Y)])
points = np.array([[x,y] for x, y in zip(b.x, b.y)])

In [172]:
sdw = minis(coords, points,4)

Optimization terminated successfully.
         Current function value: 0.031576
         Iterations: 915
         Function evaluations: 1328
[[ 0.20642149  0.2042506 ]
 [ 1.18151933  0.19849912]
 [-0.07968755  1.04299219]
 [-0.2274587  -0.3772475 ]]


In [173]:
coords = np.array([[0.5,x,y, x*y] for x, y in zip(c.X, c.Y)])
points = np.array([[x,y] for x, y in zip(c.x, c.y)])
sdw = minis(coords, points, 4)

Optimization terminated successfully.
         Current function value: 0.073001
         Iterations: 932
         Function evaluations: 1352
[[ 0.25090079  0.26414552]
 [ 1.13285911  0.17606828]
 [-0.08335907  0.99892484]
 [-0.15711155 -0.31771659]]


In [132]:
sdw

array([[0.15288631, 0.1253483 ],
       [0.13170837, 0.10273026],
       [0.41515152, 0.58312534],
       [0.35729171, 0.54529322],
       [0.85867609, 0.88347422],
       [0.90793249, 0.96460586],
       [0.17138149, 0.37686822],
       [0.01149564, 0.31957954],
       [0.89189574, 0.50010975],
       [0.89275698, 0.52728133],
       [0.84962876, 0.13480747],
       [0.90646675, 0.04852086],
       [0.20791937, 0.87841713],
       [0.06494046, 0.76985432],
       [0.62734038, 0.87170568],
       [0.63039965, 0.90438864],
       [0.61479294, 0.07186186],
       [0.62812634, 0.03744038],
       [0.3701105 , 0.82493482],
       [0.36286978, 0.8306843 ],
       [0.64360908, 0.64095734],
       [0.6212269 , 0.62430913],
       [0.49885876, 0.19234134],
       [0.36015661, 0.09987303],
       [0.30019001, 0.3713596 ],
       [0.29423585, 0.36892339],
       [0.96482872, 0.47633092],
       [0.86088615, 0.4067519 ],
       [0.13943878, 0.80277502],
       [0.02793305, 0.73356228],
       [0.

In [2]:
def mini(xy, points):
    
    def ft(a):
        a = a.reshape(2,2)
        coords = np.matmul(xy,a)
        distance = []
        dists = np.sum((coords[:, np.newaxis, :] - points[np.newaxis, ::])**2, axis = 2)
        for i in dists:
            distance.append(np.min(i))
        return sum(distance)/len(distance)
    
    transfer = optim(ft, np.eye(2))
    transfer = transfer.reshape(2,2)
    print(transfer)
    C = np.matmul(xy, transfer)
    return C 
    
    

In [3]:
def mini3(xy, points):
    
    def ft(a):
        a = a.reshape(3,2)
        coords = np.matmul(xy,a)
        distance = []
        dists = np.sum((coords[:, np.newaxis, :] - points[np.newaxis, ::])**2, axis = 2)
        for i in dists:
            distance.append(np.min(i))
        return sum(distance)/len(distance)
    
    transfer = optim(ft, np.ones([3,2]))
    transfer = transfer.reshape(3,2)
    print(transfer)
    C = np.matmul(xy, transfer)
    return C 
    
    

In [72]:
def mini4(xy, points):
    
    def ft(a):
        a = a.reshape(4,2)
        coords = np.matmul(xy,a)
        dists = np.sum((coords - points)**2, axis = 1)
        return sum(dists)
    
    transfer = optim(ft, np.ones([4,2]))
    transfer = transfer.reshape(4,2)
    print(transfer)
    C = np.matmul(xy, transfer)
    return C 
    
    